**4.1 Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.

In [ ]:
def toFeet(num):
    """
    Converts meters to feet.

    Parameters:
    num (float): The value in meters to convert.

    Returns:
    float: The value converted to feet.
    """
    return num * 3.281

def toMeters(num):
    """
    Converts feet to meters.

    Parameters:
    num (float): The value in feet to convert.

    Returns:
    float: The value converted to meters.
    """
    return num / 3.281

def toPounds(num):
    """
    Converts kilograms to pounds.

    Parameters:
    num (float): The value in kilograms to convert.

    Returns:
    float: The value converted to pounds.
    """
    return num * 2.205

def toKgs(num):
    """
    Converts pounds to kilograms.

    Parameters:
    num (float): The value in pounds to convert.

    Returns:
    float: The value converted to kilograms.
    """
    return num / 2.205

def toGallons(num):
    """
    Converts liters to gallons.

    Parameters:
    num (float): The value in liters to convert.

    Returns:
    float: The value converted to gallons.
    """
    return num / 3.785

def toLiters(num):
    """
    Converts gallons to liters.

    Parameters:
    num (float): The value in gallons to convert.

    Returns:
    float: The value converted to liters.
    """
    return num * 3.785

try:
    num = float(input("Enter the value: ")) # Take input from the user

    print("Choose an operation: a(m to ft), b(ft to m), c(kg to lbs), d(lbs to kg), e(lts to gal), f(gal to ltrs)")
    operation = input("Enter operator: ")

    #Conversion operations
    if operation == "a":
        print(f"Result: {toFeet(num)}ft")
    elif operation == "b":
        print(f"Result: {toMeters(num)}m")
    elif operation == "c":
        print(f"Result: {toPounds(num)}lbs")
    elif operation == "d":
        print(f"Result: {toKgs(num)}kg")
    elif operation == "e":
        print(f"Result: {toGallons(num)}gal")
    elif operation == "f":
        print(f"Result: {toLiters(num)}ltrs")
    else:
        print("Invalid conversion types")  # For invalid operation
except:
    print("Invalid input")# For invalid input


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

In [14]:
from statistics import mean

def sumList(user_list):
    """Returns the sum of all numbers in the list."""
    return sum(user_list)

def average(user_list):
    """Returns the average (mean) of all numbers in the list."""
    return mean(user_list)

def minimum(user_list):
    """Returns the smallest number in the list."""
    return min(user_list)

def maximum(user_list):
    """Returns the largest number in the list."""
    return max(user_list)

# Take input and convert it to a list of numbers
user_input = input("Enter elements separated by space: ").split()

try:
    # Convert string list to int list
    user_list = [int(num) for num in user_input]

    print("Choose an operation: sum, average, minimum, maximum")
    operation = input("Enter operator: ").strip().lower()

    # Perform selected operation
    if operation == "sum":
        print(f"Sum: {sumList(user_list)}")
    elif operation == "average":
        print(f"Average: {average(user_list)}")
    elif operation == "minimum":
        print(f"Minimum: {minimum(user_list)}")
    elif operation == "maximum":
        print(f"Maximum: {maximum(user_list)}")
    else:
        print("Invalid operation type.")
except:
    print("Enter valid numbers.")

Enter elements separated by space: 2 4 6
Choose an operation: sum, average, minimum, maximum
Enter operator: average
Average: 4


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [17]:
'''
  Function that extracts every other element from a list
  '''
def extract_every_other(lst):
    alternate_list = [lst[i] for i in range(len(lst)) if i % 2 == 0]
    return alternate_list

lst = input("Enter elements separated by space: ").split() #taking user input
print("Original List:", lst)

print(f"The alternate list is: {extract_every_other(lst)}")


Enter elements separated by space: 1 2 3 4 5 6
Original List: ['1', '2', '3', '4', '5', '6']
The alternate list is: ['1', '3', '5']


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [19]:
def get_sublist(lst, start, end):
  ''' function that returns a sublist from a given list'''
    sub_list = lst[start:end+1]
    return sub_list

# Get user input and split it into a list
lst = input("Enter elements separated by space: ").split()
print("Original List:", lst)

start= int(input("Enter the start index: "))# start index
end= int(input("Enter the end index: ")) #end index

print(f"The sub list is: {get_sublist(lst, start, end)}")

Enter elements separated by space: 1 2 3 4 5 6 7 8
Original List: ['1', '2', '3', '4', '5', '6', '7', '8']
Enter the start index: 2
Enter the end index: 5
The sub list is: ['3', '4', '5', '6']


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.

In [20]:
def reverse_list(lst):
  '''Python function that reverses a list using slicing'''
    rev_list = lst[::-1]
    return rev_list

# Get user input and split it into a list
lst = input("Enter elements separated by space: ").split()
print("Original List:", lst)

print(f"The sub list is: {reverse_list(lst)}")

Enter elements separated by space: 1 2 3 4 5
Original List: ['1', '2', '3', '4', '5']
The sub list is: ['5', '4', '3', '2', '1']


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

In [23]:
def remove_first_last(lst):
  ''' Python function that removes the first and last elements of a list'''
  lst.pop(0) #First element
  lst.pop(-1) #Last element
  return lst

# Get user input and split it into a list
lst = input("Enter elements separated by space: ").split()
print("Original List:", lst)

print(f"The sub list is: {remove_first_last(lst)}")

Enter elements separated by space: 1 2 3 4 5
Original List: ['1', '2', '3', '4', '5']
The sub list is: ['2', '3', '4']


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [24]:
def get_first_n(lst, n):
  '''Python function that extracts the first n elements from a list.'''
    sub_list = lst[:n] # extracting till n
    return sub_list

# Get user input and split it into a list
lst = input("Enter elements separated by space: ").split()
print("Original List:", lst)

n = int(input("Enter the number of elements: "))
print(f"The sub list is: {get_first_n(lst, n)}")


Enter elements separated by space: 1 2 3 4 5
Original List: ['1', '2', '3', '4', '5']
Enter the number of elements: 2
The sub list is: ['1', '2']


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [25]:
def get_last_n(lst, n):
  '''Python function that extracts the last n elements of a list'''
    sub_list = lst[-n:]
    return sub_list

# Get user input and split it into a list
lst = input("Enter elements separated by space: ").split()
print("Original List:", lst)

n = int(input("Enter the number of elements: "))#Number of elements for extracting
print(f"The sub list is: {get_last_n(lst, n)}")


Enter elements separated by space: 1 2 3 4 5
Original List: ['1', '2', '3', '4', '5']
Enter the number of elements: 2
The sub list is: ['4', '5']


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

In [27]:
def reverse_skip(lst):
  '''Python function that extracts a list of elements in reverse order starting
  from the second-to-last element and skipping one element in between'''
  lst.reverse() #Reversing the list
  lst.pop(0) #Deleting the first value
  reverse_list = [lst[i] for i in range(len(lst)) if i % 2 == 0] #skipping one element in between
  return reverse_list

# Get user input and split it into a list
lst = input("Enter elements separated by space: ").split()
print("Original List:", lst)

print(f"The reverse list is: {reverse_skip(lst)}")

Enter elements separated by space: 1 2 3 4 5 6
Original List: ['1', '2', '3', '4', '5', '6']
The sub list is: ['5', '3', '1']


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [32]:
def flatten_list(lst):
  '''Python function that flattens a nested list into a single list'''
    flatten_list = [val for sublist in lst for val in sublist]
    return flatten_list

list_size=int(input("enter the size of list: "))
sub_size= int(input("enter the size of sublist: "))
lst=[]
sublist=[]
#Looping through each sublist
for i in range(list_size):
    for j in range(sub_size):
        sublist.append(input("Enter a number: "))#Entering elements
    lst.append(sublist)
    sublist=[]
print (f"The original list is: {lst}")

print(f"The flattened list is: {flatten_list(lst)}")

enter the size of list: 2
enter the size of sublist: 3
Enter a number: 6
Enter a number: 8
Enter a number: 9
Enter a number: 1
Enter a number: 0
Enter a number: 4
The original list is: [['6', '8', '9'], ['1', '0', '4']]
The flattened list is: ['6', '8', '9', '1', '0', '4']


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.

In [42]:
def access_nested_element(lst, indices):
  '''Python function that extracts a specific element from a nested list given its indices'''
  row,col=indices[0],indices[1]
  return lst[row][col]

#For nested list
list_size=int(input("enter the size of list: "))
sub_size= int(input("enter the size of sublist: "))

lst=[]
sublist=[]
for i in range(list_size):
    for j in range(sub_size):
        sublist.append(input("Enter a number: ")) #Appending elements
    lst.append(sublist)
    sublist=[]
print (f"The original list is: {lst}")

indices = list(map(int, input("Enter the indices separated by space: ").split())) #for indices

print(f"The indices are:", indices)

print(f"The index value is: {access_nested_element(lst, indices)}")

enter the size of list: 2
enter the size of sublist: 3
Enter a number: 2
Enter a number: 3
Enter a number: 4
Enter a number: 5
Enter a number: 6
Enter a number: 7
The original list is: [['2', '3', '4'], ['5', '6', '7']]
Enter the indices separated by space: 1 1
The indices are: [1, 1]
The index value is: 6


Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [56]:
def sum_nested(lst):
    """
    Returns the sum of all numbers in a nested list.

    Parameters:
    lst (list): A nested list containing numbers.

    Returns:
    int: Sum of all numbers.
    """
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += int(i)  # Sum
    return total

# For nested list
list_size = int(input("Enter the size of the main list: "))
sub_size = int(input("Enter the size of each sublist: "))

lst = []
for i in range(list_size):
    sublist = []
    for j in range(sub_size):
        sublist.append(int(input(f"Enter a number for lst[{i}][{j}]: ")))  # Appending elements
    lst.append(sublist)

print(f"The original list is: {lst}")

# Calling the function and printing
print(f"The sum is: {sum_nested(lst)}")

Enter the size of the main list: 2
Enter the size of each sublist: 2
Enter a number for lst[0][0]: 1
Enter a number for lst[0][1]: 2
Enter a number for lst[1][0]: 3
Enter a number for lst[1][1]: 4
The original list is: [[1, 2], [3, 4]]
The sum is: 10


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.

In [58]:
def remove_element(lst, elem):
  '''Python function that removes all occurrences of a specific element'''
    for i in range(len(lst)):
        lst[i] = [x for x in lst[i] if x != elem] #Removing elements with the value of elem
    return lst

#For nested list
list_size = int(input("Enter the size of list: "))
sub_size = int(input("Enter the size of sublist: "))

lst = []
for i in range(list_size):
    sublist = []
    for j in range(sub_size):
        sublist.append(int(input("Enter a number: ")))  #Appending elements
    lst.append(sublist)

print(f"The original list is: {lst}")

elem = int(input("Enter the element to be removed: "))#element to be removed

print(f"The removed list is: {remove_element(lst, elem)}")

Enter the size of list: 2
Enter the size of sublist: 2
Enter a number: 1
Enter a number: 2
Enter a number: 2
Enter a number: 5
The original list is: [[1, 2], [2, 5]]
Enter the element to be removed: 2
The removed list is: [[1], [5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list.

In [59]:
def find_max(lst):
  '''Python function that finds the maximum element in a nested list'''
  max=0
  for i in lst: #Looping to check for the max value
    if(type(i)==list):
      for j in i:
        if(type(j)==list):
          for k in j:
            if(k>max):
              max=k
        else:
          if(j>max):
            max=j
    else:
      if(i>max):
        max=i
  return max
lst = [[1, 2], [3, [4, 5]], 6]
print(f"The maximum value is: {find_max(lst)}") #calling and printing

The maximum value is: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.

In [63]:
def count_occurences(lst, elem):
  '''Python function that counts the occurrences of an element in a nested list'''
  num=0
  for i in range(len(lst)):  #Looping through the list
        if [x for x in lst[i] if x == elem]: #checking for values the same as elem
          num+=1 #counting the occurences
  return num

lst = [[1, 2], [2, 3], [2, 4]]
elem = int(input("Enter the element to be counted: "))

print(f"The total occurance of {elem} is: {count_occurences(lst, elem)}")

Enter the element to be counted: 2
The total occurance of 2 is: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [65]:
def deep_flatten(lst):
  '''Python function that flattens a list of lists of lists into a single list'''
  flatten_list=[]
  # Loop through each element in the list
  for i in lst:
    if(type(i)==list):
      for j in i:
        if(type(j)==list):
          for k in j:
            flatten_list.append(k)
        else:
          flatten_list.append(j)
    else:
      flatten_list.append(i)
  return flatten_list

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

print(f"The flattened list is: {deep_flatten(lst)}")

The flattened list is: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.

In [66]:
def average_nested(lst):
  '''Python function that calculates the average of all elements in a nested list'''
  average=0
  sum=0
  length=0
  for i in lst:
    for j in i:
      sum+=j
      length+=1
  average=sum/length # Calculating average
  return average

lst = [[1, 2], [3, 4], [5, 6]]
print(average_nested(lst))

3.5


**Basic Vector and Matrix Operation with Numpy.**

Initialize an empty array with size 2X2.

In [1]:
import numpy as np

matrix = np.empty([2, 2]) #creating an empty array with 2*2 dimensions
print(matrix)

[[2.08211714e-316 0.00000000e+000]
 [8.90029543e-307 1.67626279e+243]]


Initialize an all one array with size 4X2.

In [ ]:
matrix = np.ones((4,2)) # Creating an all one array
print(matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
matrix = np.full([2, 2], 3, dtype = int) #new array with value 3
print("\nMatrix: \n", matrix)


Matrix: 
 [[3 3]
 [3 3]]


Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
array = np.ones((4,2))

print("\nGiven array: \n", array)

like_array = np.zeros_like(array) #new array of zeros
print("\n Zeros Array: \n", like_array)


Given array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 Zeros Array: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
array = np.zeros((2,2))

print("\nGiven array: \n", array)

ones_array = np.ones_like(array) #creating new array of ones
print("\n Ones Array: \n", ones_array)


Given array: 
 [[0. 0.]
 [0. 0.]]

 Ones Array: 
 [[1. 1.]
 [1. 1.]]


For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]

arr = np.array(new_list) #converting to array

print(arr)

[1 2 3 4]


Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
array= np.arange(10 , 49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Create a 3X3 matrix with values ranging from 0 to 8.

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

reshaped_arr = np.reshape(arr, (3, 3)) #reshaping the array
print(reshaped_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3) #Creating a 3*3 identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
array = np.random.random(30) #random array with size 30
print("\n Random array: \n", array)

print("Mean of the random array: ", np.mean(array)) #mean of the array


 Random array: 
 [0.78074407 0.35379227 0.85473011 0.76779206 0.0997462  0.00525313
 0.73599752 0.64107303 0.05311948 0.86631265 0.20436943 0.69419224
 0.29367227 0.02707054 0.30470726 0.03197503 0.89977187 0.55185604
 0.70547181 0.10368524 0.98004093 0.95931534 0.43657252 0.82119129
 0.81308753 0.12207507 0.42555554 0.18941524 0.94092374 0.96718114]
Mean of the random array:  0.5210230205916336


Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
array = np.random.rand(10, 10)
print("\n Random array: \n", array)

print("\n The minimum value of the array is: ", np.min(array)) #minimum vlaue
print("\n The maximum value of the array is: ", np.max(array)) #maximum value


 Random array: 
 [[9.14624192e-01 5.33738316e-01 3.82416502e-01 3.11174260e-01
  5.20046417e-01 1.69835805e-01 2.92786464e-01 1.64582949e-01
  8.57500634e-01 7.46828268e-01]
 [1.50323020e-01 3.91839065e-01 7.11211599e-01 6.45907283e-04
  9.67478128e-01 1.69322431e-01 6.18250523e-01 8.04055587e-01
  5.70485072e-01 6.36265520e-01]
 [3.73203136e-01 3.18768882e-01 4.63276158e-01 9.46413271e-01
  4.60718276e-01 4.75505832e-01 4.68059606e-01 9.99147672e-01
  1.55732940e-01 5.15172154e-02]
 [3.26048337e-01 2.12740129e-01 2.95794621e-01 6.04457221e-01
  7.31721446e-01 8.91302424e-01 2.71065084e-02 4.88711974e-01
  3.72347517e-01 6.85834436e-01]
 [5.53284609e-01 6.67817692e-01 6.90639375e-01 9.38518986e-01
  9.58880479e-01 4.51563172e-01 6.94268896e-01 3.63086061e-03
  3.71315400e-01 8.15992987e-01]
 [6.50656190e-01 3.79349684e-01 3.89153412e-01 7.64542222e-01
  3.97431546e-01 5.45476874e-01 9.91874484e-01 8.21379578e-01
  7.93959120e-01 9.00303274e-01]
 [5.43335699e-01 7.60735049e-01 3.613122

Create a zero array of size 10 and replace 5th element with 1.

In [3]:
array = np.zeros(10)
print("\n Original Array: \n", array)

array[4] = 20 #Replacing the 5th element
print("\n Replaced Array: \n", array)


 Original Array: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 Replaced Array: 
 [ 0.  0.  0.  0. 20.  0.  0.  0.  0.  0.]


Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1,2,0,0,4,0])

print("\nThe flipped Array is: \n", np.flip(arr)) #Reversing the array


The flipped Array is: 
 [0 4 0 0 2 1]


Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr = np.ones((3, 3))

print("Original array:")
print(arr)

print("Modified array:")
arr[1:-1, 1:-1] = 0 #Modifying the array with 1 on border and 0 inside

print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Modified array:
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr = np.zeros((8, 8), dtype=int)

print("Checkerboard pattern:")
#filling it with checkerboard pattern
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
# Adding the arrays and printing them
print("\n The addition between the arrays x and y are:\n ", np.add(x, y))
print("\n The addition between the arrays v and w are:\n ", np.add(v, w))


 The addition between the arrays x and y are:
  [[ 6  8]
 [10 13]]

 The addition between the arrays v and w are:
  [20 22]


Subtract the two array.

In [ ]:
#Subtracting the two array
print("\n The subtraction between the arrays x and y are:\n ", np.subtract(x, y))
print("\n The subtraction between the arrays v and w are:\n ", np.subtract(v, w))


 The subtraction between the arrays x and y are:
  [[-4 -4]
 [-4 -3]]

 The subtraction between the arrays v and w are:
  [-2 -2]


Multiply the array with any integers of your choice.

In [ ]:
#Multiplying the arrays with 4
print("\n The multiuplication of arrays x with 4 is:\n ", np.multiply(x, 4))
print("\n The multiuplication of arrays y with 4 is:\n ", np.multiply(y, 4))
print("\n The multiuplication of arrays v with 4 is:\n ", np.multiply(v, 4))
print("\n The multiuplication of arrays w with 4 is:\n ", np.multiply(w, 4))


 The multiuplication of arrays x with 4 is:
  [[ 4  8]
 [12 20]]

 The multiuplication of arrays y with 4 is:
  [[20 24]
 [28 32]]

 The multiuplication of arrays v with 4 is:
  [36 40]

 The multiuplication of arrays w with 4 is:
  [44 48]


Find the square of each element of the array.

In [ ]:
print("\n The square of each element of array x is:\n ", np.square(x))
print("\n The square of each element of array y is:\n ", np.square(y))
print("\n The square of each element of array v is:\n ", np.square(v))
print("\n The square of each element of array w is:\n ", np.square(w))


 The square of each element of array x is:
  [[ 1  4]
 [ 9 25]]

 The square of each element of array y is:
  [[25 36]
 [49 64]]

 The square of each element of array v is:
  [ 81 100]

 The square of each element of array w is:
  [121 144]


Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
#Finding the dot product of 2 arrays
print("\n The dot product between the arrays v and w are:\n ", np.dot(v, w))
print("\n The dot product between the arrays x and v are:\n ", np.dot(x, v))
print("\n The dot product between the arrays x and y are:\n ", np.dot(x, y))


 The dot product between the arrays v and w are:
  219

 The dot product between the arrays x and v are:
  [29 77]

 The dot product between the arrays x and y are:
  [[19 22]
 [50 58]]


Concatenate x(and)y along row and Concatenate v(and)w along column.

In [ ]:
print("\nConcatenate along rows:\n ", np.vstack((x, y)))
print("\nConcatenate along columns:\n ", np.hstack((v, w)))


Concatenate along rows:
  [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate along columns:
  [ 9 10 11 12]


Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
print("\nConcatenate:\n ", np.concatenate((x, v)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Because the dimensions are not the same. x is a 2-dimensional array and v is a one-dimensional array.

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

In [5]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("A.A−1 = I")
inv_A = np.linalg.inv(A) #Finding the inverse of A
dot_A= np.dot(A, inv_A) #Multiplying A with its inverse
result = np.round(dot_A)
print(result)

print("\nAB ̸= BA")
dot_AB = np.dot(A, B)#Finding the dot product of AB
dot_BA = np.dot(B, A)#Finding the dot product of BA
print("\nAB:\n", dot_AB)
print("\nBA:\n", dot_BA)

print("\n(AB)T = BTAT")
transpose_AB = dot_AB.transpose() #Finding the transpose of AB
print("\nAB transpose:\n", transpose_AB)
transpose_B = B.transpose()
transpose_A = A.transpose()
dot_TATB = np.dot(transpose_B, transpose_A)#Finding the dot product of BT and AT
print("\nB transpose dot A transpose:\n", dot_TATB)

A.A−1 = I
[[1. 0.]
 [0. 1.]]

AB ̸= BA

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)T = BTAT

AB transpose:
 [[23 51]
 [13 29]]

B transpose dot A transpose:
 [[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

In [ ]:
#Finding the value of x, y, z according to X = A-1.B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = ([[-1],
      [-3],
      [9]])

inv_A = np.linalg.inv(A)#Finding the inverse of A

X = np.dot(inv_A, B)#Finding the dot product of A inverse and B

print("Solution: x =", X[0], ", y =", X[1], ", z =", X[2]) #Printing the values

Solution: x = [2.] , y = [1.] , z = [-2.]
